const pidgin = {
  // terminal
  Nn: [
    "ʻĀina",
    "aloha",
    "aloha shirt",
    "aunty",
    "bento",
    "brah",
    "buggah",
    "da kine",
    "fadda",
    "grindz",
    "hale",
    "hanabata days",
    "haole",
    "haupia",
    "imu",
    "kamaʻāina",
    "kane",
    "keiki",
    "kuleana",
    "lanai",
    "lei",
    "li hing mui",
    "lilikoi",
    "lumpia",
    "mainland",
    "makai",
    "mauka",
    "moke",
    "musubi",
    "ohana",
    "okole",
    "opala",
    "pali",
    "pancit",
    "poke",
    "puka",
    "pupu",
    "shoyu",
    "sole",
    "tako",
    "tita",
    "unko",
    "vog",
    "wahine",
    "wasabi",
  ], // noun
  V: [
    "bocha",
    "da kine",
    "fut",
    "get",
    "palu",
    "holo holo",
    "jan ken po",
    "pau",
    "scrap",
    "shaka",
    "shishi",
    "stink eye",
    "talk story",
  ], // verb
  Aj: [
    "broke da mout",
    "buss up",
    "choke",
    "da kine",
    "ewa",
    "hamajang",
    "hapa",
    "irk",
    "junk",
    "kapu",
    "leeward",
    "lolo",
    "make",
    "on hawaiian time",
    "ono",
    "small kine",
  ],
  In: ["wit", "on", "fo", "wen", "down", "off"], //preposition
  Ar: ["da", "wan", "ho bah wan", "da kine"], // article
  Ph: ["can handle?", "howzit?", "k den", "like beef?", "moke action"], //phrase
  Ex: [
    "aisus!",
    "aurite!",
    "chee-hoo!",
    "ho bah",
    "rajah dat!",
    "shoots!",
    "tanks!",
  ],
  Av: [
    "kanak attack",
    "an' den",
    "bumbai you",
    "garans",
    "halala",
    "hana hou",
    "l'dat",
    "lickings",
    "pau hana",
  ],

  // non terminal
  NP: ["#Ar# #Nn#", "#Ar# #Aj# #Nn#", "#Nn#"],
  VP: ["#V# #NP#", "#V# #PP#"],
  PP: ["#In# #NP#"],
  SP: ["#Ph#.", "#Ex#"],

  // origin
  S: ["#NP# #VP#.", "#NP# #VP#.", "#NP# #VP#.", "#NP# #VP#.", "#SP#"],
}

export default pidgin
